deploy:
  provider: heroku
  api_key:
    secure: ZvbGoBU11+0o26R19Cq+7CTqmTajCmTc/0hYlYFnbXLdPmhK+Iug3Xvf2wg8LWqZPt3whaqapHfRUcKFNX/IemxKzCGFtq1GNb5iRFtQfuT2jPg7MpyJOpvQfuwx7JVzIYnyPvDZYTxVGI7F+zcQ08Ta6XzWsxiAMme76YkKzougpkt/v4sGlSb9r7cHmuFfj6Ik44y2OAuErALPJkqxmavne+8kpI25WtxckjPCo0e4DGKLWw4Mw26UM3IffqbPtJrbgDA1PhDfw57/8FzE3dBu8aAlSVlHtOpR9awJ91puAI1JvV46+9/1zGoz3GiQabpWY3muGO4qKv4AD2LMV2p5OGDgV29j+T05o/9MnQ1NIpseuK3TyURiaoNOuD1JpDfIOSvLXIOzW6szHJfP0oBshZT0RqfCi95BBR7wUFHKa33Y2JABfSVxwpUbrVmbyPit9AtcoNrK9KSo79U4NeArNChrFjz0pBqhIi8huc0WSZ4SBNJMyrQOQ8ra/EIxxTExd2BneXeTorqWQpSPnBHeKVcqzrDbmRp1nd7uGwiJrcybdob7E+m3bQDTIeUYe/I/y2qpzI8QFgL0u8jSkJSCUhuI8k0g2HBuH3zeMAGR1QwV+6/Ogk5MPHlduzK8lFip2e6WDSCXoIsmjO52UPB+PTU9ZrmSxuxgKqSsRcA=
  app: 
    master: linx-thelibrarian-staging
    production: linx-thelibrarian